#!/usr/bin/env python3
"""Regenerate the tool block in each skill's intro from the tool fixture.

The block between `<!-- tools:begin` and `<!-- tools:end -->` in each
plugins/*/skills/clax/SKILL.md names the plugin version (from that
plugin's manifest) and every tool in plugins/pi/test/fixtures/contract.json,
with the harness's naming. `clax doctor --agent <x>` reads the version and
tool count from this block in the installed skill.

It also checks, in both modes, that the hand-written tool lists in
docs/contract.md and the READMEs name exactly the fixture's tools and spell out
their count. scripts/test-plugins.sh runs it with --check.

Usage: scripts/sync-skill-tools.py [--check]
  --check  change nothing; exit 1 naming each skill whose block is stale
"""
import json
import os
import re
import sys
import textwrap

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURE = "plugins/pi/test/fixtures/contract.json"
BEGIN = "<!-- tools:begin: generated by scripts/sync-skill-tools.py from " + FIXTURE + " -->"
END = "<!-- tools:end -->"

# skill, manifest carrying its version, tool-name prefix, where the tools come from
SKILLS = [
    ("plugins/claude-code/skills/clax/SKILL.md", "plugins/claude-code/.claude-plugin/plugin.json", "",
     "as the `clax` MCP server"),
    ("plugins/clax/skills/clax/SKILL.md", "plugins/clax/.codex-plugin/plugin.json", "",
     "as the `clax` MCP server"),
    ("plugins/pi/skills/clax/SKILL.md", "plugins/pi/package.json", "clax_",
     "from the Clax Pi extension, named `clax_<tool>`"),
    ("plugins/clax-grok/skills/clax/SKILL.md", "plugins/clax-grok/.grok-plugin/plugin.json", "",
     "as the `clax_grok` MCP server"),
]


def block(manifest, prefix, source, tools):
    version = json.load(open(os.path.join(ROOT, manifest)))["version"]
    names = ", ".join("`" + prefix + t + "`" for t in tools)
    text = f"This is Clax plugin {version}. It provides {len(tools)} tools {source}: {names}."
    return "\n".join([BEGIN, *textwrap.wrap(text, 78, break_on_hyphens=False), END])


# (file, a regex matching the list's opening words, whose group 1 is the
# spelled-out count; the prefix the list's tool names carry)
DOC_LISTS = [
    ("docs/contract.md", r"^([A-Z][a-z-]+) tools: ", ""),
    ("docs/usage.md", r"^Each harness gets the same ([a-z-]+) tools", ""),
    ("plugins/claude-code/README.md", r"^- The `clax` MCP server [^\n]*?: ([a-z-]+) tools", ""),
    ("plugins/clax/README.md", r"^- The `clax` MCP server [^\n]*?: ([a-z-]+) tools", ""),
    ("plugins/pi/README.md", r"^- ([A-Z][a-z-]+) tools: ", "clax_"),
    ("plugins/clax-grok/README.md", r"^- The `clax_grok` MCP server [^\n]*?: ([a-z-]+) tools", ""),
]
ONES = ("zero one two three four five six seven eight nine ten eleven twelve thirteen "
        "fourteen fifteen sixteen seventeen eighteen nineteen").split()
TENS = {"twenty": 20, "thirty": 30, "forty": 40, "fifty": 50}


def number(word):
    word = word.lower()
    if word in ONES:
        return ONES.index(word)
    tens, _, ones = word.partition("-")
    return TENS.get(tens, -1000) + (ONES.index(ones) if ones in ONES else 0 if not ones else -1000)


def names(text, prefix=""):
    # Server names, and Grok's `use_tool`, which a list may name beside the tools.
    found = set(re.findall(r"`([a-z_]+)`", text)) - {"clax", "clax_grok", "use_tool"}
    return {n[len(prefix):] for n in found if n.startswith(prefix)}


def doc_problems(tools):
    problems = []
    for path, opening, prefix in DOC_LISTS:
        text = open(os.path.join(ROOT, path)).read()
        # Each opening matches within one line, so it cannot span paragraphs.
        m = re.search(opening, text, re.M)
        if not m:
            problems.append(f"{path}: no tool list matching {opening!r}")
            continue
        # The paragraph, or the list item, that the opening words start.
        para = re.split(r"\n\n|\n- ", text[m.start():], maxsplit=1)[0]
        listed = names(para, prefix)
        if number(m.group(1)) != len(tools) or listed != set(tools):
            problems.append(f"{path}: says {m.group(1)!r} tools; missing "
                            f"{sorted(set(tools) - listed)}, extra {sorted(listed - set(tools))}")
    return problems


def main():
    if sys.argv[1:] not in ([], ["--check"]):
        print("usage: scripts/sync-skill-tools.py [--check]", file=sys.stderr)
        sys.exit(2)
    check = sys.argv[1:] == ["--check"]
    tools = [t["name"] for t in json.load(open(os.path.join(ROOT, FIXTURE)))["tools"]]
    stale = []
    for skill, manifest, prefix, source in SKILLS:
        path = os.path.join(ROOT, skill)
        text = open(path).read()
        start, end = text.find("<!-- tools:begin"), text.find(END)
        if start < 0 or end < start:
            print(f"{skill}: no tools block ({BEGIN} ... {END})")
            stale.append(skill)
            continue
        new = text[:start] + block(manifest, prefix, source, tools) + text[end + len(END):]
        if new != text:
            stale.append(skill)
            if not check:
                open(path, "w").write(new)
    failed = False
    if check and stale:
        print("stale tool blocks (run scripts/sync-skill-tools.py): " + ", ".join(stale))
        failed = True
    for problem in doc_problems(tools):
        print(problem)
        failed = True
    if failed:
        sys.exit(1)


main()
